# Generated by Django 3.0.1 on 2020-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2083)),
                ('image', models.FileField(upload_to='static/images/')),
                ('status', models.IntegerField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
