# Generated by Django 3.0.1 on 2020-01-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolutionapp', '0003_auto_20200102_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='static/images/')),
                ('status', models.BooleanField(default=True)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fav_icon', models.FileField(upload_to='static/images')),
                ('content', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
