# Generated by Django 3.0.1 on 2020-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolutionapp', '0004_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fav_icon',
            field=models.FileField(help_text='Please upload image size is <b>50 X 50 </b> only.', upload_to='static/images'),
        ),
    ]
